apiVersion: v2
name: cloudflare-operator
description: Cloudflare operator — meta-operator + bundled controllers
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/jacaudi/cloudflare-operator
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 5.0.1
