/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v2alpha1

// init registers all CRD type pairs (root + List) with the package's SchemeBuilder.
// Co-located here rather than in each _types.go because the SchemeBuilder.Register
// signature requires runtime.Object (DeepCopyObject), which is generated by
// controller-gen in zz_generated.deepcopy.go — so registration must follow codegen.
func init() {
	SchemeBuilder.Register(
		&CloudflareOperator{}, &CloudflareOperatorList{},
		&CloudflareZone{}, &CloudflareZoneList{},
		&CloudflareZoneConfig{}, &CloudflareZoneConfigList{},
		&CloudflareDNSRecord{}, &CloudflareDNSRecordList{},
		&CloudflareRuleset{}, &CloudflareRulesetList{},
		&CloudflareTunnel{}, &CloudflareTunnelList{},
	)
}
