---
apiVersion: cloudflare.io/v1alpha1
kind: CloudflareZone
metadata:
  name: example-zone
spec:
  name: "example.com"
  type: "full"
  deletionPolicy: Retain
  interval: 30m
  # The referenced Secret must include both `apiToken` and `accountID` keys.
  secretRef:
    name: cloudflare-api-token
