package v1alpha1

// init registers all CRD type pairs (root + List) with the package's SchemeBuilder.
// Co-located here rather than in each _types.go because the SchemeBuilder.Register
// signature requires runtime.Object (DeepCopyObject), which is generated by
// controller-gen in zz_generated.deepcopy.go — so registration must follow codegen.
func init() {
	SchemeBuilder.Register(
		&CloudflareOperator{}, &CloudflareOperatorList{},
		&CloudflareZone{}, &CloudflareZoneList{},
		&CloudflareZoneConfig{}, &CloudflareZoneConfigList{},
		&CloudflareDNSRecord{}, &CloudflareDNSRecordList{},
		&CloudflareRuleset{}, &CloudflareRulesetList{},
		&CloudflareTunnel{}, &CloudflareTunnelList{},
	)
}
