//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BotManagementSettings) DeepCopyInto(out *BotManagementSettings) {
	*out = *in
	if in.EnableJS != nil {
		in, out := &in.EnableJS, &out.EnableJS
		*out = new(bool)
		**out = **in
	}
	if in.FightMode != nil {
		in, out := &in.FightMode, &out.FightMode
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BotManagementSettings.
func (in *BotManagementSettings) DeepCopy() *BotManagementSettings {
	if in == nil {
		return nil
	}
	out := new(BotManagementSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNSRecord) DeepCopyInto(out *CloudflareDNSRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNSRecord.
func (in *CloudflareDNSRecord) DeepCopy() *CloudflareDNSRecord {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNSRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareDNSRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNSRecordList) DeepCopyInto(out *CloudflareDNSRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareDNSRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNSRecordList.
func (in *CloudflareDNSRecordList) DeepCopy() *CloudflareDNSRecordList {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNSRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareDNSRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNSRecordSpec) DeepCopyInto(out *CloudflareDNSRecordSpec) {
	*out = *in
	if in.ZoneRef != nil {
		in, out := &in.ZoneRef, &out.ZoneRef
		*out = new(ZoneReference)
		**out = **in
	}
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.Proxied != nil {
		in, out := &in.Proxied, &out.Proxied
		*out = new(bool)
		**out = **in
	}
	if in.SRVData != nil {
		in, out := &in.SRVData, &out.SRVData
		*out = new(SRVData)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
	out.SecretRef = in.SecretRef
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNSRecordSpec.
func (in *CloudflareDNSRecordSpec) DeepCopy() *CloudflareDNSRecordSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNSRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareDNSRecordStatus) DeepCopyInto(out *CloudflareDNSRecordStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareDNSRecordStatus.
func (in *CloudflareDNSRecordStatus) DeepCopy() *CloudflareDNSRecordStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareDNSRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRuleset) DeepCopyInto(out *CloudflareRuleset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRuleset.
func (in *CloudflareRuleset) DeepCopy() *CloudflareRuleset {
	if in == nil {
		return nil
	}
	out := new(CloudflareRuleset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareRuleset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRulesetList) DeepCopyInto(out *CloudflareRulesetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareRuleset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRulesetList.
func (in *CloudflareRulesetList) DeepCopy() *CloudflareRulesetList {
	if in == nil {
		return nil
	}
	out := new(CloudflareRulesetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareRulesetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRulesetSpec) DeepCopyInto(out *CloudflareRulesetSpec) {
	*out = *in
	if in.ZoneRef != nil {
		in, out := &in.ZoneRef, &out.ZoneRef
		*out = new(ZoneReference)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]RulesetRuleSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.SecretRef = in.SecretRef
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRulesetSpec.
func (in *CloudflareRulesetSpec) DeepCopy() *CloudflareRulesetSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareRulesetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareRulesetStatus) DeepCopyInto(out *CloudflareRulesetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareRulesetStatus.
func (in *CloudflareRulesetStatus) DeepCopy() *CloudflareRulesetStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareRulesetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnel) DeepCopyInto(out *CloudflareTunnel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnel.
func (in *CloudflareTunnel) DeepCopy() *CloudflareTunnel {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelList) DeepCopyInto(out *CloudflareTunnelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareTunnel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelList.
func (in *CloudflareTunnelList) DeepCopy() *CloudflareTunnelList {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelRule) DeepCopyInto(out *CloudflareTunnelRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelRule.
func (in *CloudflareTunnelRule) DeepCopy() *CloudflareTunnelRule {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnelRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelRuleList) DeepCopyInto(out *CloudflareTunnelRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareTunnelRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelRuleList.
func (in *CloudflareTunnelRuleList) DeepCopy() *CloudflareTunnelRuleList {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnelRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelRuleSpec) DeepCopyInto(out *CloudflareTunnelRuleSpec) {
	*out = *in
	out.TunnelRef = in.TunnelRef
	if in.Hostnames != nil {
		in, out := &in.Hostnames, &out.Hostnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Backend.DeepCopyInto(&out.Backend)
	if in.OriginRequest != nil {
		in, out := &in.OriginRequest, &out.OriginRequest
		*out = new(TunnelRuleOriginRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(TunnelRuleSourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelRuleSpec.
func (in *CloudflareTunnelRuleSpec) DeepCopy() *CloudflareTunnelRuleSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelRuleStatus) DeepCopyInto(out *CloudflareTunnelRuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelRuleStatus.
func (in *CloudflareTunnelRuleStatus) DeepCopy() *CloudflareTunnelRuleStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelSpec) DeepCopyInto(out *CloudflareTunnelSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Connector != nil {
		in, out := &in.Connector, &out.Connector
		*out = new(ConnectorSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = new(TunnelRoutingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelSpec.
func (in *CloudflareTunnelSpec) DeepCopy() *CloudflareTunnelSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelStatus) DeepCopyInto(out *CloudflareTunnelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Connector != nil {
		in, out := &in.Connector, &out.Connector
		*out = new(ConnectorStatus)
		**out = **in
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelStatus.
func (in *CloudflareTunnelStatus) DeepCopy() *CloudflareTunnelStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZone) DeepCopyInto(out *CloudflareZone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZone.
func (in *CloudflareZone) DeepCopy() *CloudflareZone {
	if in == nil {
		return nil
	}
	out := new(CloudflareZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareZone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneConfig) DeepCopyInto(out *CloudflareZoneConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneConfig.
func (in *CloudflareZoneConfig) DeepCopy() *CloudflareZoneConfig {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareZoneConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneConfigList) DeepCopyInto(out *CloudflareZoneConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareZoneConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneConfigList.
func (in *CloudflareZoneConfigList) DeepCopy() *CloudflareZoneConfigList {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareZoneConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneConfigSpec) DeepCopyInto(out *CloudflareZoneConfigSpec) {
	*out = *in
	if in.ZoneRef != nil {
		in, out := &in.ZoneRef, &out.ZoneRef
		*out = new(ZoneReference)
		**out = **in
	}
	out.SecretRef = in.SecretRef
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(SSLSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecuritySettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Performance != nil {
		in, out := &in.Performance, &out.Performance
		*out = new(PerformanceSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.BotManagement != nil {
		in, out := &in.BotManagement, &out.BotManagement
		*out = new(BotManagementSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneConfigSpec.
func (in *CloudflareZoneConfigSpec) DeepCopy() *CloudflareZoneConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneConfigStatus) DeepCopyInto(out *CloudflareZoneConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneConfigStatus.
func (in *CloudflareZoneConfigStatus) DeepCopy() *CloudflareZoneConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneList) DeepCopyInto(out *CloudflareZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareZone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneList.
func (in *CloudflareZoneList) DeepCopy() *CloudflareZoneList {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneSpec) DeepCopyInto(out *CloudflareZoneSpec) {
	*out = *in
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = new(bool)
		**out = **in
	}
	out.SecretRef = in.SecretRef
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneSpec.
func (in *CloudflareZoneSpec) DeepCopy() *CloudflareZoneSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareZoneStatus) DeepCopyInto(out *CloudflareZoneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NameServers != nil {
		in, out := &in.NameServers, &out.NameServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OriginalNameServers != nil {
		in, out := &in.OriginalNameServers, &out.OriginalNameServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ActivatedOn != nil {
		in, out := &in.ActivatedOn, &out.ActivatedOn
		*out = (*in).DeepCopy()
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareZoneStatus.
func (in *CloudflareZoneStatus) DeepCopy() *CloudflareZoneStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorImage) DeepCopyInto(out *ConnectorImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorImage.
func (in *ConnectorImage) DeepCopy() *ConnectorImage {
	if in == nil {
		return nil
	}
	out := new(ConnectorImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorSpec) DeepCopyInto(out *ConnectorSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ConnectorImage)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorSpec.
func (in *ConnectorSpec) DeepCopy() *ConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorStatus) DeepCopyInto(out *ConnectorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorStatus.
func (in *ConnectorStatus) DeepCopy() *ConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinifySettings) DeepCopyInto(out *MinifySettings) {
	*out = *in
	if in.CSS != nil {
		in, out := &in.CSS, &out.CSS
		*out = new(string)
		**out = **in
	}
	if in.HTML != nil {
		in, out := &in.HTML, &out.HTML
		*out = new(string)
		**out = **in
	}
	if in.JS != nil {
		in, out := &in.JS, &out.JS
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinifySettings.
func (in *MinifySettings) DeepCopy() *MinifySettings {
	if in == nil {
		return nil
	}
	out := new(MinifySettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSettings) DeepCopyInto(out *NetworkSettings) {
	*out = *in
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(string)
		**out = **in
	}
	if in.WebSockets != nil {
		in, out := &in.WebSockets, &out.WebSockets
		*out = new(string)
		**out = **in
	}
	if in.PseudoIPv4 != nil {
		in, out := &in.PseudoIPv4, &out.PseudoIPv4
		*out = new(string)
		**out = **in
	}
	if in.IPGeolocation != nil {
		in, out := &in.IPGeolocation, &out.IPGeolocation
		*out = new(string)
		**out = **in
	}
	if in.OpportunisticOnion != nil {
		in, out := &in.OpportunisticOnion, &out.OpportunisticOnion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSettings.
func (in *NetworkSettings) DeepCopy() *NetworkSettings {
	if in == nil {
		return nil
	}
	out := new(NetworkSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceSettings) DeepCopyInto(out *PerformanceSettings) {
	*out = *in
	if in.CacheLevel != nil {
		in, out := &in.CacheLevel, &out.CacheLevel
		*out = new(string)
		**out = **in
	}
	if in.BrowserCacheTTL != nil {
		in, out := &in.BrowserCacheTTL, &out.BrowserCacheTTL
		*out = new(int)
		**out = **in
	}
	if in.Minify != nil {
		in, out := &in.Minify, &out.Minify
		*out = new(MinifySettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Polish != nil {
		in, out := &in.Polish, &out.Polish
		*out = new(string)
		**out = **in
	}
	if in.Brotli != nil {
		in, out := &in.Brotli, &out.Brotli
		*out = new(string)
		**out = **in
	}
	if in.EarlyHints != nil {
		in, out := &in.EarlyHints, &out.EarlyHints
		*out = new(string)
		**out = **in
	}
	if in.HTTP2 != nil {
		in, out := &in.HTTP2, &out.HTTP2
		*out = new(string)
		**out = **in
	}
	if in.HTTP3 != nil {
		in, out := &in.HTTP3, &out.HTTP3
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceSettings.
func (in *PerformanceSettings) DeepCopy() *PerformanceSettings {
	if in == nil {
		return nil
	}
	out := new(PerformanceSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetRuleSpec) DeepCopyInto(out *RulesetRuleSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ActionParameters != nil {
		in, out := &in.ActionParameters, &out.ActionParameters
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetRuleSpec.
func (in *RulesetRuleSpec) DeepCopy() *RulesetRuleSpec {
	if in == nil {
		return nil
	}
	out := new(RulesetRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SRVData) DeepCopyInto(out *SRVData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRVData.
func (in *SRVData) DeepCopy() *SRVData {
	if in == nil {
		return nil
	}
	out := new(SRVData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLSettings) DeepCopyInto(out *SSLSettings) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.MinTLSVersion != nil {
		in, out := &in.MinTLSVersion, &out.MinTLSVersion
		*out = new(string)
		**out = **in
	}
	if in.TLS13 != nil {
		in, out := &in.TLS13, &out.TLS13
		*out = new(string)
		**out = **in
	}
	if in.AlwaysUseHTTPS != nil {
		in, out := &in.AlwaysUseHTTPS, &out.AlwaysUseHTTPS
		*out = new(string)
		**out = **in
	}
	if in.AutomaticHTTPSRewrites != nil {
		in, out := &in.AutomaticHTTPSRewrites, &out.AutomaticHTTPSRewrites
		*out = new(string)
		**out = **in
	}
	if in.OpportunisticEncryption != nil {
		in, out := &in.OpportunisticEncryption, &out.OpportunisticEncryption
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLSettings.
func (in *SSLSettings) DeepCopy() *SSLSettings {
	if in == nil {
		return nil
	}
	out := new(SSLSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySettings) DeepCopyInto(out *SecuritySettings) {
	*out = *in
	if in.SecurityLevel != nil {
		in, out := &in.SecurityLevel, &out.SecurityLevel
		*out = new(string)
		**out = **in
	}
	if in.ChallengeTTL != nil {
		in, out := &in.ChallengeTTL, &out.ChallengeTTL
		*out = new(int)
		**out = **in
	}
	if in.BrowserCheck != nil {
		in, out := &in.BrowserCheck, &out.BrowserCheck
		*out = new(string)
		**out = **in
	}
	if in.EmailObfuscation != nil {
		in, out := &in.EmailObfuscation, &out.EmailObfuscation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySettings.
func (in *SecuritySettings) DeepCopy() *SecuritySettings {
	if in == nil {
		return nil
	}
	out := new(SecuritySettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelReference) DeepCopyInto(out *TunnelReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelReference.
func (in *TunnelReference) DeepCopy() *TunnelReference {
	if in == nil {
		return nil
	}
	out := new(TunnelReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelRoutingSpec) DeepCopyInto(out *TunnelRoutingSpec) {
	*out = *in
	if in.DefaultBackend != nil {
		in, out := &in.DefaultBackend, &out.DefaultBackend
		*out = new(TunnelRuleBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.OriginRequest != nil {
		in, out := &in.OriginRequest, &out.OriginRequest
		*out = new(TunnelRuleOriginRequest)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelRoutingSpec.
func (in *TunnelRoutingSpec) DeepCopy() *TunnelRoutingSpec {
	if in == nil {
		return nil
	}
	out := new(TunnelRoutingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelRuleBackend) DeepCopyInto(out *TunnelRuleBackend) {
	*out = *in
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(TunnelRuleServiceRef)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.HTTPStatus != nil {
		in, out := &in.HTTPStatus, &out.HTTPStatus
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelRuleBackend.
func (in *TunnelRuleBackend) DeepCopy() *TunnelRuleBackend {
	if in == nil {
		return nil
	}
	out := new(TunnelRuleBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelRuleOriginRequest) DeepCopyInto(out *TunnelRuleOriginRequest) {
	*out = *in
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelRuleOriginRequest.
func (in *TunnelRuleOriginRequest) DeepCopy() *TunnelRuleOriginRequest {
	if in == nil {
		return nil
	}
	out := new(TunnelRuleOriginRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelRuleServiceRef) DeepCopyInto(out *TunnelRuleServiceRef) {
	*out = *in
	out.Port = in.Port
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelRuleServiceRef.
func (in *TunnelRuleServiceRef) DeepCopy() *TunnelRuleServiceRef {
	if in == nil {
		return nil
	}
	out := new(TunnelRuleServiceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TunnelRuleSourceRef) DeepCopyInto(out *TunnelRuleSourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TunnelRuleSourceRef.
func (in *TunnelRuleSourceRef) DeepCopy() *TunnelRuleSourceRef {
	if in == nil {
		return nil
	}
	out := new(TunnelRuleSourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneReference) DeepCopyInto(out *ZoneReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneReference.
func (in *ZoneReference) DeepCopy() *ZoneReference {
	if in == nil {
		return nil
	}
	out := new(ZoneReference)
	in.DeepCopyInto(out)
	return out
}
